### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by PeculiarPineTreePlays** [UnRealDinnerbone/SimpleZoom#9]
Why did you change the license?
SimpleZoom used to be MIT, but now it's pretty close to "all rights reserved".

The reason I started using SimpleZoom was because of Optifine's restrictive licensing.
Specifically, Optifine says "Use of this mod... as a part of any public display is strictly prohibited..."
I'm not a lawyer, but that would seem to say using Optifine in YouTube videos is probably technically illegal.
So I went looking for an open-source zoom mod, and found SimpleZoom.

But now, looks like I'll need to find a different zoom mod.
I'm curious why the change?

**Comment by UnRealDinnerbone** [comment]
Because I have had issues in the past where people copied others code tweaked like two lines and realized it. 
I still want people to see my code (which is why the code is visible, but you cant just take the code)
the jars themself are under "All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks".
Only the youtube thing I have no idea how the works Illegal but public displays of the mod are fine
